export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InJhZmFlbCIsImVtYWlsIjoicmFmYWVsQGVtYWlsLmNvbSIsImlhdCI6MTY4NTY1ODQ1NiwiZXhwIjoxNjg2MjYzMjU2LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.a72dEtjbRAF3KlC6UDehZ3Cl_YSrNaqcwBYFMl1_pOs';
